spring:
  application:
    name: xc-mini
  http:
    encoding:
      force: true
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
      location: /home/webapps/xc-minin/temp_files
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: dev
  thymeleaf:
    cache: false

server:
  tomcat:
    max-threads: 600
    uri-encoding: utf-8
    accesslog:
      enabled: true
      directory: logs
  port: 8081
  context-path: /xc/mini

---
spring:
  profiles: dev
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: wx-mini
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000

---
spring:
  profiles: test
  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      uri: mongodb://xc-mini-test:xc-mini-test@172.17.0.13:28018/xc-mini-test
  redis:
    host: 172.17.0.13
    port: 6379
    timeout: 3000
    password: QTBLB6qU

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /home/logs/xc-mini
---
spring:
  profiles: prod
  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      uri: mongodb://xc-mini:VQfqhUq2@172.17.0.13:28018/xc-mini
  redis:
    host: 172.17.0.13
    port: 6379
    timeout: 3000
    password: QTBLB6qU

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /home/logs/xc-mini
