spring:
  application:
    name: xc-mini
  http:
    encoding:
      force: true
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
      location: /home/webapps/xc/minin/temp_files
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: dev
  thymeleaf:
    cache: false

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: wx-mini
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

server:
  tomcat:
    max-threads: 600
    uri-encoding: utf-8
    accesslog:
      enabled: true
      directory: logs
  port: 8081
  context-path: /xc/mini

---
spring:
  profiles: dev
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: wx-mini
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

---
spring:
  profiles: test
  data:
    mongodb:
      host: 172.17.0.13
      port: 27017
      database: wx-mini-test
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /home/logs/xc-mini
---
spring:
  profiles: prod
  data:
    mongodb:
      host: 172.17.0.13
      port: 27017
      database: wx-mini
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /home/logs/xc-mini
