spring:
  application:
    name: xc-manage
  http:
    encoding:
      force: true
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
      location: /home/webapps/xc-manage/temp_files
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: dev
  thymeleaf:
    cache: false

server:
  tomcat:
    max-threads: 200
    uri-encoding: utf-8
    accesslog:
      enabled: true
      directory: logs
  port: 8082
  context-path: /xc/manage

---
spring:
  profiles: dev
  http:
    multipart:
      location: /Users/guoqw/netease/docs/技术工作组项目/日志平台/test
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: wx-mini
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

---
spring:
  profiles: test
  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      uri: mongodb://xc-mini-test:xc-mini-test@172.17.0.13:28018/xc-mini-test

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /home/logs/xc-manage
---
spring:
  profiles: prod
  data:
    mongodb:
      #      host: 172.17.0.13
      #      port: 28018
      #      database: wx-mini
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      uri: mongodb://xc-mini:VQfqhUq2@172.17.0.13:28018/xc-mini

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /home/logs/xc-manage
